package proc

// rawMainTinyGo is the template for main_tinygo.go
// This is injected into the user's Source directory during build
const rawMainTinyGo = `// Auto-generated by pdgoc - do not edit
// This file provides the entry points for the Playdate device

package main

import (
	"unsafe"

	"github.com/playdate-go/pdgo"
)

//export go_init
func go_init(playdate unsafe.Pointer) {
	pd = pdgo.Init(playdate)
	initGame()
	pdgo.SetUpdateCallback(update)
}

//export go_update
func go_update(userdata unsafe.Pointer) int {
	_ = userdata
	return pdgo.CallUpdateCallback()
}
`
